### ISSUE TITLE
Support Ouster lidar

### ISSUE THREAD

**Issue by amacneil** [foxglove/community#745]
via @jtbandes:

We currently support Velodyne packets. We should add support for Ouster too.

See:
- https://github.com/cruise-automation/webviz/issues/162, https://github.com/cruise-automation/webviz/issues/675 (similar webviz feature requests)
- https://data.ouster.io/downloads/software-user-manual/lidar-packet-format-update.pdf
- https://github.com/ouster-lidar/ouster_example

**Comment by thomasegriffith** [comment]
+1 to the original request.  

I'd argue that for a lot of use cases it's way more efficient from a data footprint and computation perspective to only publish raw packets instead of `PointCloud` or `PointCloud2` messages... and then if one needs to visualize a point cloud, make the visualizer decode the packets into a point cloud.
